### ISSUE TITLE
kurento-utils-js getUserMedia function not found with latest adapter.js

### ISSUE THREAD

**Issue by mikesi** [Kurento/bugtracker#118]
**KMS Version**:

6.5

I get:
ReferenceError: getUserMedia is not defined
 /bower_components/kurento-utils/js/kurento-utils.js:412:13 getMedia()
 /bower_components/kurento-utils/js/kurento-utils.js:418:13 WebRtcPeerSendonly.WebRtcPeer()
 /bower_components/kurento-utils/js/kurento-utils.js:533:31 new WebRtcPeerSendonly()
 

If i use the latest adapter.js, if I use and older one it works OK.

**Comment by Nek-** [comment]
Hello,

This is not really an issue as you used the wrong version of adapter.js. But well, the kurento utils lib should really be updated as the 0.2.9 version of adapter.js is really TOOOOOOO old (and browsers are gonna cut retro compatiblity on some api it uses).

Btw, the changes should also be report to the v6.2.0 of the kurento utils api.

**Comment by acv-binhnv** [comment]
replace getUserMedia into navigator.getUserMedia

**Comment by igracia** [comment]
This was solved 2 weeks ago. You can see the patch [here](https://github.com/Kurento/kurento-utils-js/commit/a5cadd89a1bd041ea9d5b3b30198be816a10b5fe).

**Comment by creedarky** [comment]
@igracia is there a planned date to release a new version of `kurento-utils-js`? In the version published in npm it's still showing that error if you use a bundler like webpack, I installed directly from master for now

**Comment by igracia** [comment]
Yap, it should be there probably next week. Sorry for the trouble and the delay!

**Comment by creedarky** [comment]
Thank you!

**Comment by igracia** [comment]
It's released already!

**Comment by mars00772** [comment]
I was try a demo,but still got the error, what should be done? @igracia ,thank you~~!
```
{
  "name": "kurento-composite-node-example",
  "version": "5.1.1-dev",
  "private": true,
  "scripts": {
    "postinstall": "cd static && bower install"
  },
  "dependencies": {
    "express": "~3.2.6",
    "kurento-client": "6.6.0",
    "minimist": "^1.1.0",
    "ws": "~0.4.32"
  },
  "devDependencies": {
    "bower": "~1.7.9"
  }
}

```
